@startuml
'https://plantuml.com/class-diagram
!theme vibrant
Amministratore "1" - "1" Ristorante
Ristorante "1" - "1" Menu
Menu "1" - "*" Categorie
Categorie "1" - "*" Pietanze
Ristorante "1" - "*" Dipendenti
Ristorante "1" - "*" Ordini
Ordini "1" -- "*" Pietanze
Pietanze "*" -- "1" Ristorante
Dipendenti "1" -- "*" Ordini


class Amministratore {
String email
String password
}

class Dipendenti {
String nome
String cognome
String email
String password
Ruolo ruolo
bool primologin
}

class Ristorante {
String nome
}

class Menu {
String link
}

class Categorie{
String nome
}

class Pietanze{
String nome
String descrizione
Integer costo
String[] allergeni
}

class Ordini{
Integer numerotavolo
Timestamp dataeora
}


enum Ruolo {
  Addetto alla Sala
  Addetto alla Cucina
  Supervisore
}

@enduml